const productsData = [
    {
      id: 1,
      name: 'Product 1',
      description: 'Description of Product 1',
      price: 19.99,
      imageUrl: '/image1.jpg',
      brand: "Dr Batra's",
      discount: '10%',
      uses: ['Use A'],
      rating: 3.5,
      inWishlist: false,
    },
    {
      id: 2,
      name: 'Product 2',
      description: 'Description of Product 2',
      price: 29.99,
      imageUrl: '/image2.jpg',
      brand: 'Maxisoft',
      discount: '20%',
      uses: ['Use B'],
      rating: 3.7,
      inWishlist: true,
    },
    {
      id: 3,
      name: 'Product 3',
      description: 'Description of Product 3',
      price: 39.99,
      imageUrl: '/image1.jpg',
      brand: 'Dr. Rashel',
      discount: '30%',
      uses: ['Use C'],
    },
    {
      id: 4,
      name: 'Product 4',
      description: 'Description of Product 4',
      price: 49.99,
      imageUrl: '/image1.jpg',
      brand: 'Foxtale ',
      discount: '40%',
      uses: ['Use D'],
    },
    {
      id: 5,
      name: 'Product 5',
      description: 'Description of Product 5',
      price: 59.99,
      imageUrl: '/image1.jpg',
      brand: 'Nivea',
      discount: '50%',
      uses: ['Use E'],
    },
    // Add more products as needed
    {
      id: 6,
      name: 'Product 6',
      description: 'Description of Product 6',
      price: 69.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand F',
      discount: '60%',
      uses: ['Use F'],
    },
    {
      id: 7,
      name: 'Product 7',
      description: 'Description of Product 7',
      price: 79.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand G',
      discount: '70%',
      uses: ['Use G'],
    },
    {
      id: 8,
      name: 'Product 8',
      description: 'Description of Product 8',
      price: 89.99,
      imageUrl: '/image1.jpg',
      brand: "Dr Batra's",
      discount: '80%',
      uses: ['Use H'],
    },
    {
      id: 9,
      name: 'Product 9',
      description: 'Description of Product 9',
      price: 99.99,
      imageUrl: '/image1.jpg',
      brand: "Dr Batra's",
      discount: '90%',
      uses: ['Use I'],
    },
    {
      id: 10,
      name: 'Product 10',
      description: 'Description of Product 10',
      price: 109.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand J',
      discount: '5%',
      uses: ['Use J'],
    },
    {
      id: 11,
      name: 'Product 11',
      description: 'Description of Product 11',
      price: 119.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand K',
      discount: '15%',
      uses: ['Use K'],
    },
    {
      id: 12,
      name: 'Product 12',
      description: 'Description of Product 12',
      price: 129.99,
      imageUrl: '/image1.jpg',
      brand: "Dr Batra's",
      discount: '25%',
      uses: ['Use L'],
    },
    {
      id: 13,
      name: 'Product 13',
      description: 'Description of Product 13',
      price: 139.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand M',
      discount: '35%',
      uses: ['Use M'],
    },
    {
      id: 14,
      name: 'Product 14',
      description: 'Description of Product 14',
      price: 149.99,
      imageUrl: '/image1.jpg',
      brand: 'Vi-John',
      discount: '45%',
      uses: ['Use N'],
    },
    {
      id: 15,
      name: 'Product 15',
      description: 'Description of Product 15',
      price: 159.99,
      imageUrl: '/image1.jpg',
      brand: 'Vi-John',
      discount: '55%',
      uses: ['Use O'],
    },
    {
      id: 16,
      name: 'Product 16',
      description: 'Description of Product 16',
      price: 169.99,
      imageUrl: '/image1.jpg',
      brand: "Dr Batra's",
      discount: '65%',
      uses: ['Use P'],
    },
    {
      id: 17,
      name: 'Product 17',
      description: 'Description of Product 17',
      price: 179.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand Q',
      discount: '75%',
      uses: ['Use Q'],
    },
    {
      id: 18,
      name: 'Product 18',
      description: 'Description of Product 18',
      price: 189.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand R',
      discount: '85%',
      uses: ['Use R'],
    },
    {
      id: 19,
      name: 'Product 19',
      description: 'Description of Product 19',
      price: 199.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand S',
      discount: '95%',
      uses: ['Use S'],
    },
    {
      id: 20,
      name: 'Product 20',
      description: 'Description of Product 20',
      price: 209.99,
      imageUrl: '/image1.jpg',
      brand: 'Brand T',
      discount: '10%',
      uses: ['Use T'],
    },
  ];
  
  export default productsData;
  
